# save-settings/settings.yml
repository:

  rulesets:
    - name: Default
      target: branch
      enforcement: active

      conditions:
        ref_name:
          include:
            - ~DEFAULT_BRANCH
          exclude: []

      rules:
        - type: deletion
        - type: non_fast_forward # prevents force pushes

    - name: Pull Requests
      target: branch
      enforcement: active

      conditions:
        ref_name:
          include:
            - ~DEFAULT_BRANCH
          exclude: []