# This settings file can be used to create org-level settings

# This is the settings that need to be applied to all repositories in the org
# See https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository for all available settings for a repository
repository:
  auto_init: true
  security:
    enableVulnerabilityAlerts: true
    enableAutomatedSecurityFixes: true
  has_issues: false
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true


# The following attributes are applied to any repo within the org
# So if a repo is not listed above is created or edited
# The app will apply the following settings to it
labels:
  # Labels: define labels for Issues and Pull Requests
  include:
    - name: bug
      color: CC0000
      description: An issue with the system
    - name: feature
      # If including a `#`, make sure to wrap it with quotes!
      color: "#336699"
      description: New functionality.

autolinks:
  - key_prefix: "SAB-"
    url_template: "https://unibuddy.atlassian.net/browse/SAB-<num>"
    is_alphanumeric: false

rulesets:
  - name: Default
    target: branch
    # enforcement: active

    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []

    rules:
      - type: deletion
      # - type: required_linear_history
      # - type: pull_request
      #   parameters:
      #     dismiss_stale_reviews_on_push: true
      #     require_code_owner_review: true
      #     required_approving_review_count: 1
      #     required_review_thread_resolution: true
      # - type: required_status_checks
      #   parameters:
      #     strict_required_status_checks_policy: true
      # - type: non_fast_forward # prevents force pushes

  # - name: Pull Requests
  #   target: branch
  #   enforcement: active

  #   conditions:
  #     ref_name:
  #       include:
  #         - ~DEFAULT_BRANCH
  #       exclude: []